services:
  - type: web
    name: travel-system-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
